#thymeleaf
spring:
  thymeleaf:
    mode: HTML5
    encoding: UTF-8
    servlet:
      content-type: text/html
    cache: false
  datasource:
    url: jdbc:mysql://94.191.94.87:3306/fresh?useUnicode=true&characterEncoding=utf8&serverTimezone=GMT
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: 
    password: 
#context
server:
  servlet:
    context-path: /

#pagehelper config
pagehelper:
  helperDialect: mysql
  reasonable: true
  supportMethodsArguments: true
  params: count=countSql

#mybatis
mybatis:
  type-aliases-package: com.store.fresh.entity
  mapper-locations: classpath:mappers/*.xml
# print sql
logging:
  level:
     com.store.fresh.mapper : debug




